# version: "3.9"
services:
  api:
    image: web_api
    container_name: web_api_application
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Postgres123
    volumes:
      - ./Api/Data/TwitterCloneDB.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"